In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/graduate-admissions/Admission_Predict.csv
/kaggle/input/graduate-admissions/Admission_Predict_Ver1.1.csv
/kaggle/input/red-wine-quality-cortez-et-al-2009/winequality-red.csv


In [3]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split , GridSearchCV
from sklearn.metrics import accuracy_score , confusion_matrix , roc_auc_score , roc_curve
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

In [4]:
data = pd.read_csv('/kaggle/input/red-wine-quality-cortez-et-al-2009/winequality-red.csv')

In [5]:
data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [6]:
x = data.drop(columns='quality')

In [7]:
y= data.quality

In [8]:
x_train , x_test, y_train,y_test = train_test_split(x,y,random_state = 20)

In [9]:
knn = KNeighborsClassifier()

In [10]:
import pickle
pickle.dump(knn, open("knn.pkl" , "wb"))

In [11]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [12]:
knn.score(x_test, y_test)

0.5175

In [13]:
knn1 = KNeighborsClassifier()

In [14]:
knn1.fit(x_train,y_train)

KNeighborsClassifier()

In [15]:
pickle.dump(knn1,open('knn1.pkl' , 'wb'))

In [16]:
pram  = {
    'n_neighbors':[3,5,7,9,12,13,15,17,21],
    'p' : [1,2],
    'weights' : ['uniform', 'distance']
    
    
    
}

In [17]:
grid_cv = GridSearchCV(knn,param_grid=pram )

In [18]:
grid_cv.fit(x_train, y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [3, 5, 7, 9, 12, 13, 15, 17, 21],
                         'p': [1, 2], 'weights': ['uniform', 'distance']})

In [19]:
grid_cv.best_params_

{'n_neighbors': 21, 'p': 1, 'weights': 'distance'}

In [20]:
knn = KNeighborsClassifier(n_neighbors=21,p= 1 ,weights='distance' , leaf_size=10 , algorithm='auto')

In [21]:
knn.fit(x_train,y_train)

KNeighborsClassifier(leaf_size=10, n_neighbors=21, p=1, weights='distance')

In [22]:
knn.score(x_test,y_test)

0.6325

In [23]:
pwd

'/kaggle/working'

In [24]:
ls

__notebook_source__.ipynb  knn.pkl  knn1.pkl


In [25]:
knn.predict([x_test.iloc[0]])

/opt/conda/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([6])

In [26]:
x_test.iloc[0]

fixed acidity            7.10000
volatile acidity         0.27000
citric acid              0.60000
residual sugar           2.10000
chlorides                0.07400
free sulfur dioxide     17.00000
total sulfur dioxide    25.00000
density                  0.99814
pH                       3.38000
sulphates                0.72000
alcohol                 10.60000
Name: 1508, dtype: float64

In [27]:
data 

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [28]:
from sklearn.svm import SVC

In [29]:
svc= SVC()
svc.fit(x_train,y_train)

SVC()

In [30]:
svc.score(x_test,y_test)

0.5

In [31]:
param ={"kernel":['linear', 'poly', 'rbf', 'sigmoid' ]} 
svm_grid = GridSearchCV(svc , param_grid=param , verbose=3 )
svm_grid.fit(x_train,y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits
[CV 1/5] END .....................kernel=linear;, score=0.583 total time=   8.2s
[CV 2/5] END .....................kernel=linear;, score=0.533 total time=   6.8s
[CV 3/5] END .....................kernel=linear;, score=0.571 total time=  10.9s
[CV 4/5] END .....................kernel=linear;, score=0.592 total time=   9.1s
[CV 5/5] END .....................kernel=linear;, score=0.556 total time=   7.2s
[CV 1/5] END .......................kernel=poly;, score=0.500 total time=   0.1s
[CV 2/5] END .......................kernel=poly;, score=0.487 total time=   0.2s
[CV 3/5] END .......................kernel=poly;, score=0.475 total time=   0.2s
[CV 4/5] END .......................kernel=poly;, score=0.475 total time=   0.1s
[CV 5/5] END .......................kernel=poly;, score=0.515 total time=   0.2s
[CV 1/5] END ........................kernel=rbf;, score=0.512 total time=   0.1s
[CV 2/5] END ........................kernel=rbf;,

GridSearchCV(estimator=SVC(),
             param_grid={'kernel': ['linear', 'poly', 'rbf', 'sigmoid']},
             verbose=3)

In [32]:
svm_grid.best_params_

{'kernel': 'linear'}

In [33]:
svc1 = SVC(kernel='poly')
svc1.fit(x_train,y_train)

SVC(kernel='poly')

In [34]:
svc1.score(x_test,y_test)

0.49

In [35]:
x_train

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
400             6.6             0.735         0.02            7.90      0.122   
35              7.8             0.645         0.00            5.50      0.086   
641             9.5             0.590         0.44            2.30      0.071   
721             8.9             0.480         0.24            2.85      0.094   
1501            7.8             0.820         0.29            4.30      0.083   
...             ...               ...          ...             ...        ...   
924             8.6             0.470         0.27            2.30      0.055   
1247            7.4             0.550         0.19            1.80      0.082   
271            11.5             0.180         0.51            4.00      0.104   
474            10.5             0.280         0.51            1.70      0.080   
1379            7.5             0.570         0.02            2.60      0.077   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
400                  68.0                 124.0  0.99940  3.47       0.53   
35                    5.0                  18.0  0.99860  3.40       0.55   
641                  21.0                  68.0  0.99920  3.46       0.63   
721                  35.0                 106.0  0.99820  3.10       0.53   
1501                 21.0                  64.0  0.99642  3.16       0.53   
...                   ...                   ...      ...   ...        ...   
924                  14.0                  28.0  0.99516  3.18       0.80   
1247                 15.0                  34.0  0.99655  3.49       0.68   
271                   4.0                  23.0  0.99960  3.28       0.97   
474                  10.0                  24.0  0.99820  3.20       0.89   
1379                 11.0                  35.0  0.99557  3.36       0.62   

      alcohol  
400       9.9  
35        9.6  
641       9.5  
721       9.2  
1501      9.4  
...       ...  
924      11.2  
1247     10.5  
271      10.1  
474       9.4  
1379     10.8  

[1199 rows x 11 columns]

In [36]:
df = pd.read_csv('/kaggle/input/graduate-admissions/Admission_Predict_Ver1.1.csv')

In [37]:
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
495         496        332          108                  5  4.5   4.0  9.02   
496         497        337          117                  5  5.0   5.0  9.87   
497         498        330          120                  5  4.5   5.0  9.56   
498         499        312          103                  4  4.0   5.0  8.43   
499         500        327          113                  4  4.5   4.5  9.04   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
495         1              0.87  
496         1              0.96  
497         1              0.93  
498         0              0.73  
499         0              0.84  

[500 rows x 9 columns]

In [38]:
x = df.drop(df.columns[[0, 8]], axis = 1)
x

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
0          337          118                  4  4.5   4.5  9.65         1
1          324          107                  4  4.0   4.5  8.87         1
2          316          104                  3  3.0   3.5  8.00         1
3          322          110                  3  3.5   2.5  8.67         1
4          314          103                  2  2.0   3.0  8.21         0
..         ...          ...                ...  ...   ...   ...       ...
495        332          108                  5  4.5   4.0  9.02         1
496        337          117                  5  5.0   5.0  9.87         1
497        330          120                  5  4.5   5.0  9.56         1
498        312          103                  4  4.0   5.0  8.43         0
499        327          113                  4  4.5   4.5  9.04         0

[500 rows x 7 columns]

In [39]:
y = df.iloc[:,8]
y

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ... 
495    0.87
496    0.96
497    0.93
498    0.73
499    0.84
Name: Chance of Admit , Length: 500, dtype: float64

In [40]:
x_train , x_test , y_train,y_test = train_test_split(x,y,random_state = 30 , test_size = .20)

In [41]:
from sklearn.svm import SVR

In [42]:
svr = SVR()

In [43]:
svr.fit(x_train, y_train)

SVR()

In [44]:
df.isna().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [45]:
df['GRE Score'] = df['GRE Score'].fillna(df['GRE Score'].mean())

In [46]:
df['TOEFL Score'] =df['TOEFL Score'].fillna(df['TOEFL Score'].mean())

In [47]:
df['University Rating'] = df['University Rating'].fillna(df['University Rating'].mean())

In [48]:
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
495         496        332          108                  5  4.5   4.0  9.02   
496         497        337          117                  5  5.0   5.0  9.87   
497         498        330          120                  5  4.5   5.0  9.56   
498         499        312          103                  4  4.0   5.0  8.43   
499         500        327          113                  4  4.5   4.5  9.04   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
495         1              0.87  
496         1              0.96  
497         1              0.93  
498         0              0.73  
499         0              0.84  

[500 rows x 9 columns]

In [49]:
from sklearn.metrics import r2_score
r2_score(y_test ,  svr.predict(x_test))

0.685117659118474

In [50]:
svr.predict(x_test)

array([0.79359894, 0.56840662, 0.70121728, 0.64051776, 0.82877673,
       0.75720511, 0.65919306, 0.61314479, 0.73137208, 0.7450226 ,
       0.83095028, 0.68214796, 0.77285966, 0.88845842, 0.80998244,
       0.8247482 , 0.55105976, 0.5986574 , 0.75757418, 0.7159455 ,
       0.70815123, 0.70214425, 0.7920094 , 0.80912574, 0.7717613 ,
       0.56683869, 0.63246794, 0.64924208, 0.62574847, 0.58584348,
       0.6697305 , 0.53829813, 0.78952432, 0.63965643, 0.66426546,
       0.66289981, 0.65128345, 0.79695115, 0.5501086 , 0.66026974,
       0.57509407, 0.61435263, 0.67883631, 0.66912539, 0.78486554,
       0.65539903, 0.91631603, 0.63191225, 0.62692592, 0.77809513,
       0.88682892, 0.69506213, 0.79551633, 0.69391549, 0.67678932,
       0.88428817, 0.63590511, 0.53807879, 0.62764507, 0.71415275,
       0.78007972, 0.68890559, 0.73340895, 0.64024814, 0.70710604,
       0.66720127, 0.66543166, 0.62400627, 0.86396078, 0.6824248 ,
       0.52723608, 0.871495  , 0.64914782, 0.53984195, 0.64897

In [51]:
svr.predict([x.iloc[0]])

/opt/conda/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  "X does not have valid feature names, but"


array([0.88845842])

In [52]:
y[0]

0.92

In [53]:
svr.score(x_test,y_test)

0.685117659118474

# stacking 

In [54]:
import pandas as pd 
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [55]:
data = pd.read_csv('/kaggle/input/red-wine-quality-cortez-et-al-2009/winequality-red.csv')

In [56]:
data 

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [57]:
x = data.drop(columns='quality')
y = data.quality

In [58]:
train , val_train , test , val_test  = train_test_split(x,y,test_size = .50 , random_state = 30)

In [59]:
x_train , x_test , y_train, y_test = train_test_split(train ,test,random_state = 30 , test_size = .20)

In [60]:
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [61]:
knn.score(x_test,y_test)

0.54375

In [62]:
svc = SVC()
svc.fit(x_train,y_train)

SVC()

In [63]:
svc.score(x_test,y_test)

0.4875

In [64]:
predcition_knn = knn.predict(val_train)
prediction_svc = svc.predict(val_train)

In [65]:
predcition_knn

array([7, 5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 6, 5, 5, 6, 5, 5, 6,
       5, 5, 6, 6, 6, 5, 5, 6, 5, 6, 6, 5, 6, 6, 6, 6, 5, 7, 6, 6, 5, 4,
       6, 7, 6, 6, 5, 6, 5, 5, 5, 6, 5, 5, 6, 6, 5, 5, 6, 5, 5, 6, 5, 5,
       6, 6, 5, 4, 5, 5, 5, 6, 6, 6, 7, 5, 5, 6, 6, 6, 7, 6, 5, 5, 5, 6,
       5, 5, 5, 7, 6, 7, 6, 7, 5, 6, 5, 5, 5, 6, 5, 7, 6, 5, 6, 5, 7, 5,
       5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 7, 6, 5, 5, 6, 5, 5, 6, 6, 5,
       5, 6, 7, 5, 5, 5, 6, 6, 5, 5, 6, 5, 5, 5, 5, 5, 6, 7, 5, 5, 5, 5,
       6, 5, 6, 5, 4, 5, 5, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 5, 6, 5, 6, 5,
       6, 5, 5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 6, 5, 7, 5, 6, 5,
       5, 6, 6, 5, 6, 5, 5, 6, 6, 6, 6, 5, 6, 6, 5, 6, 5, 4, 5, 6, 7, 5,
       6, 6, 5, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 5, 5, 6, 5, 5, 5, 6, 5, 6,
       6, 6, 5, 6, 6, 5, 6, 5, 5, 6, 5, 6, 6, 5, 6, 6, 5, 6, 6, 5, 6, 6,
       5, 5, 6, 6, 6, 6, 5, 6, 6, 5, 5, 6, 5, 6, 5, 6, 5, 6, 6, 5, 6, 6,
       7, 5, 6, 7, 5, 4, 6, 7, 5, 5, 6, 5, 5, 6, 5,

In [66]:
prediction_svc

array([6, 6, 6, 6, 6, 5, 6, 5, 5, 5, 6, 5, 6, 6, 5, 6, 6, 5, 6, 5, 6, 6,
       6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 5, 5, 6, 5, 5, 6, 5, 6, 6, 5, 5,
       6, 6, 5, 6, 5, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 5, 6,
       5, 6, 5, 6, 5, 6, 6, 6, 5, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 5,
       5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 5, 5, 5,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 5, 6, 6, 6, 6, 5, 5, 6, 6,
       6, 6, 6, 6, 6, 6, 5, 6, 5, 5, 6, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6,
       5, 5, 6, 6, 5, 6, 6, 5, 5, 6, 6, 6, 5, 6, 5, 6, 6, 5, 6, 6, 6, 5,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 6, 5,
       6, 6, 5, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 5, 6,
       6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 6, 5, 6, 6,
       6, 5, 6, 5, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6,
       6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 5, 5, 5, 6, 5,

In [67]:
input3 = np.column_stack((predcition_knn,prediction_svc))

In [68]:
output = val_test

In [69]:
output


1147    7
659     4
871     5
1333    5
1411    6
       ..
1073    6
200     7
942     7
1106    6
1329    6
Name: quality, Length: 800, dtype: int64

In [70]:
pd.DataFrame(input3)

0  1
0    7  6
1    5  6
2    6  6
3    5  6
4    5  6
..  .. ..
795  5  6
796  5  6
797  5  6
798  6  6
799  5  5

[800 rows x 2 columns]

In [71]:
rf = RandomForestClassifier()

In [72]:
rf.fit(input3,output)

RandomForestClassifier()

In [73]:
rf.score(x_test,y_test)

/opt/conda/lib/python3.7/site-packages/sklearn/base.py:444: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


ValueError: X has 11 features, but RandomForestClassifier is expecting 2 features as input.

In [74]:
knn
svc
rf

RandomForestClassifier()

In [75]:
knn_output = knn.predict(x_test)
svc_output = svc.predict(x_test)

In [76]:
output_stack1 = np.column_stack ((knn_output,svc_output))

In [77]:
rf.predict(output_stack1)

array([5, 6, 5, 5, 6, 6, 5, 6, 6, 5, 6, 5, 5, 5, 6, 6, 6, 5, 5, 6, 5, 6,
       6, 5, 5, 5, 6, 5, 5, 5, 6, 5, 6, 5, 6, 6, 5, 5, 6, 5, 5, 6, 5, 5,
       6, 6, 5, 5, 6, 5, 6, 5, 6, 5, 5, 6, 6, 6, 6, 5, 5, 5, 5, 6, 6, 5,
       5, 5, 6, 5, 5, 5, 5, 6, 6, 6, 6, 5, 5, 5, 6, 6, 5, 6, 5, 6, 6, 5,
       6, 6, 5, 5, 6, 5, 5, 6, 6, 5, 5, 5, 5, 6, 6, 5, 6, 5, 5, 6, 6, 5,
       5, 6, 6, 5, 5, 5, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 6, 5,
       6, 6, 5, 6, 6, 5, 5, 6, 5, 5, 5, 6, 6, 5, 5, 6, 5, 6, 6, 5, 6, 6,
       5, 5, 5, 6, 5, 5])

In [78]:
rf.score(output_stack1 , y_test)

0.55

In [ ]:
https://archive.ics.uci.edu/ml/datasets/Activity+recognition+with+healthy+older+people+using+a+batteryless+wearable+sensor